[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
dex = "Ab53L5iKwJmLUGRyEX9z9tLygPHEyLDzEdjq9qk3CAB1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
